app:
  eureka-server:
    localhost
spring:
  application:
    name: api-gateway
#  web:
#    cors:
#      allowed-origins:
#        - http://localhost:3000
#        - http://localhost:4000
#      allowed-methods:
#        - GET
#        - POST
#        - PUT
#        - DELETE
#        - OPTIONS
#      allowed-headers: "*"
#      allow-credentials: true
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-coach-ticket-booking-realm
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/user/**, /aggregate/user/v3/api-docs
              filters:
                  - StripPrefix=2
            - id: coach-service
              uri: lb://COACH-SERVICE
              predicates:
                - Path=/api/v1/coaches/**, /aggregate/open-api/coaches/v3/api-docs
              filters:
                  - StripPrefix=3
            - id: discovery-server
              uri: http://eureka:password@${app.eureka-server}:8761
              predicates:
                - Path=/eureka/web
              filters:
                - SetPath=/
            - id: discovery-server-static
              uri: http://eureka:password@${app.eureka-server}:8761
              predicates:
                - Path=/eureka/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@${app.eureka-server}:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: user-service
        url: /aggregate/user/v3/api-docs
      - name: coach-service
        url: /aggregate/open-api/coaches/v3/api-docs
      - name: api-gateway
        url: /v3/api-docs

    oauth2-redirect-url: http://localhost:9000/webjars/swagger-ui/oauth2-redirect.html
    persistAuthorization: true
    oauth:
      clientId: spring-cloud-client
      clientSecret: EB1G8mOa9WW8wLhgIZTlsn60DbZyfp51
      use-basic-authentication-with-access-code-grant: true
      realm: spring-coach-ticket-booking-realm
      app-name: API Gateway Swagger
      scopes: openid, profile, email

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observation:
    key-values:
      application: api-gateway
  tracing:
    sampling:
      probability: 1.0

loki:
  url: http://localhost:3100/loki/api/v1/push

server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
