stream_over_http_enabled: true

server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    zipkin:
      endpoint: 0.0.0.0:9411  # Lắng nghe Zipkin trace trên port 9411

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 720h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks